config/routes.rb
Rails.application.routes.draw do
  root to: 'cats#index'

  resources :cats, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update]

  def index
    @cats = Cat.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.save

    redirect_to cats_path
  end

  def edit
  end

  def update
    @cat.update(cat_update_params)

    redirect_to cat_path(@cat)
  end

  private

  def set_cat
    @cat = Cat.find(params[:id])
  end

  def cat_params
    params.require(:cat).permit(:breed, :color, :legs, :description)
  end

  def cat_update_params
    params.require(:cat).permit(:breed, :color, :legs, :description, :claimed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<%= simple_form_for @cat do |f| %>
  <%= f.input :breed %>
  <%= f.input :color %>
  <%= f.input :legs %>
  <%= f.input :description %>

  <% if @cat.persisted? %>
    <%= f.input :claimed %>
  <% end %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/cats/create.html.erb
<h1>Cats#create</h1>
<p>Find me in app/views/cats/create.html.erb</p>

app/views/cats/edit.html.erb
<h1>Updating info</h1>

<%= render 'form' %>

app/views/cats/index.html.erb
<h1>Missing kitties</h1>

<%= link_to new_cat_path, class: 'btn btn-primary mb-4' do %>
  <i class="fas fa-plus"></i> Report missing cat
<% end %>

<ul class="list-unstyled">
  <% @cats.each do |cat| %>
    <li>
      <% if cat.claimed %>
        <i class="fas fa-check-square"></i>
      <% else %>
        <i class="fas fa-square"></i>
      <% end %>

      <%= link_to cat_path(cat) do %>
        <strong>
          <%= cat.color.capitalize %> <%= cat.breed %>
        </strong>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/cats/new.html.erb
<h1>Report missing cat</h1>

<%= render 'form' %>

app/views/cats/show.html.erb
<h1>Missing cat 😿</h1>
<%= link_to cats_path do %>
  <i class="fas fa-arrow-left"></i> Back
<% end %>

<p><%= link_to 'Update cat info', edit_cat_path(@cat) %></p>

<h3>Number of legs: <%= @cat.legs %></h3>
<h3>Found on: <%= @cat.created_at %></h3>

<p><%= @cat.color.capitalize %> <%= @cat.breed %></p>
<p><%= @cat.description %></p>

app/views/cats/update.html.erb
<h1>Cats#update</h1>
<p>Find me in app/views/cats/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petfinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/61b8e38b7a.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>